# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs

  extensions:
    - .coffee
    - .erb
    - .js
    - .jsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  public_output_path: packs-dev
  dev_server:
    host: 0.0.0.0
    port: 5001
    https: true
    disableHostCheck: true

test:
  <<: *default

  public_output_path: packs-test

production:
  <<: *default
